const faqs = [
  {
    q: "Is Lirefin giving me investment advice?",
    a: "No. Lirefin summarizes news articles and labels how their content reads with respect to the assets in your portfolio — bullish, neutral, or bearish — based on the text alone. Output is informational and AI-generated; it can be wrong, biased, or outdated. Treat it as a faster way to read the news, not as a recommendation.",
  },
  {
    q: "Which sites does it work on?",
    a: "Lirefin auto-detects 25+ major financial sites including Reuters, Bloomberg, CNBC, Wall Street Journal, Financial Times, MarketWatch, Yahoo Finance, Seeking Alpha, Investing.com, Barron's, Forbes, The Motley Fool, Benzinga, and more. For sites we don't recognize explicitly, it falls back to DOM heuristics — if the page reads like a financial article, the Analyze button appears anyway.",
  },
  {
    q: "What languages are supported?",
    a: "Lirefin reads articles in any language Claude understands and produces output in 13 of them: English, Turkish, German, French, Spanish, Italian, Portuguese, Dutch, Japanese, Chinese, Korean, Arabic, and Russian. Set your preferred output language in Settings.",
  },
  {
    q: "Do you log my browsing history?",
    a: "No. Lirefin only sends the text of articles you explicitly press Analyze on, plus your portfolio holdings, to our backend. We do not log article text persistently. We use a short 5-minute SHA-256 cache so re-clicking Analyze on the same article doesn't burn another credit. Your tabs, browsing history, cookies, and form data are never read.",
  },
  {
    q: "Where does the AI come from?",
    a: "All analyses are generated by Anthropic's Claude models via our backend proxy — your API key never leaves the server. We use Claude's tool-use API, which forces every response into a strict JSON schema (ticker, sentiment, confidence, reasoning, supporting quote) — that's how we keep hallucinated tickers out.",
  },
  {
    q: "How do credits work?",
    a: "Each analysis consumes credits based on the article length and the number of assets in your portfolio. New accounts ship with 25 free credits. Paid monthly plans (launching soon) give you a credit budget that resets each cycle, plus bonus credits at higher tiers.",
  },
  {
    q: "Can I cancel anytime?",
    a: "Yes. Once paid plans go live, you'll be able to upgrade, downgrade, or cancel directly from the extension's settings panel. Cancelled subscriptions remain active until the end of the current billing cycle.",
  },
  {
    q: "Do you support European or Asian tickers?",
    a: "Yes. We support US stocks and ETFs, plus European exchanges (XETRA, LSE, Euronext) and Asian exchanges (TSE, HKEX, KOSPI), backed by Finnhub. The settings panel includes a debounced ticker search so you don't have to remember exchange suffixes.",
  },
];

export function FAQ() {
  return (
    <section
      id="faq"
      className="border-b border-border/60 bg-surface-tint py-24 sm:py-32"
    >
      <div className="mx-auto w-full max-w-3xl px-6">
        <div className="text-center">
          <div className="text-[11px] font-semibold uppercase tracking-[0.22em] text-brand-700 dark:text-brand-400">
            FAQ
          </div>
          <h2 className="mt-4 text-balance text-3xl font-semibold tracking-tight text-navy-800 dark:text-white sm:text-5xl">
            Questions, answered.
          </h2>
          <p className="mt-5 text-pretty text-lg text-muted-foreground">
            Everything we&apos;d want to know before installing a finance
            extension. Still missing something? Drop us a line at{" "}
            <a
              href="mailto:hello@lirefin.com"
              className="font-medium text-navy-700 underline-offset-4 hover:underline dark:text-navy-200"
            >
              hello@lirefin.com
            </a>
            .
          </p>
        </div>

        <div className="mt-14 divide-y divide-border rounded-2xl border border-border bg-card shadow-sm">
          {faqs.map((item) => (
            <details
              key={item.q}
              className="group p-6 sm:p-7 [&_summary::-webkit-details-marker]:hidden"
            >
              <summary className="flex cursor-pointer items-center justify-between gap-4 text-left text-base font-semibold text-navy-800 dark:text-white">
                {item.q}
                <span className="ml-auto inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-border text-muted-foreground transition-all group-open:rotate-45 group-open:border-navy-500 group-open:text-navy-700 dark:group-open:text-navy-200">
                  +
                </span>
              </summary>
              <p className="mt-3 text-[14.5px] leading-relaxed text-muted-foreground">
                {item.a}
              </p>
            </details>
          ))}
        </div>
      </div>
    </section>
  );
}
